### PR TITLE
styled all pages

### LINKED ISSUE #3: Change the theme
The theme being used now is a simple light theme with the buttons coloured blue. Change the theme to something more attractive.

### PR DESCRIPTION
**Pull request by code-ash-IIT**
HomePage after login may need some changes, merge this and suggest changes of style, (Somethings are not optimised for mobile view) Fixes #3

### CODE REVIEW

**Comment by dipeshs809** [comment]
Everything seems fine, please add screenshot also.

**Review by Ritam727 — COMMENTED** [review]
In the login and register pages, the "Login" and "Register" texts do not appear exactly at the center. Please correct it if you can, rest seems fine.

**Comment by code-ash-IIT** [comment]
@dipeshs809 @Ritam727

**Review by MeenalPatidar — COMMENTED** [review]
Looks alright.

**Comment by Ritam727** [comment]
Style looks alright, the headings Login and Register seem to be a little shifted from the middle, center them if you can.

**Review by dipeshs809 — APPROVED** [review]

**Review by Ritam727 — APPROVED** [review]

**Pull request merged**
